layout_spectrum: 0.14617633409807368
typography_spectrum: 0.03910710935056726
color:
  brandStrength: 0.44653863299204644
  lightness: 0.14822903162864323
  saturation: 0.5034061758548464
  rhythmicContrast: 0.6167238793593122
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
github: true
author:
  name: James Carroll
name: '0x42'
navigation:
  - name: Github
    url: 'https://github.com/jamcar23'
    type: external
  - name: Twitter
    url: 'https://twitter.com/jamcar23'
    type: external
title: James Carroll
content: []
description: jamcar23
purpose: []
